name = "agent-arena"
pages_build_output_dir = "public"
compatibility_date = "2026-01-01"

[[d1_databases]]
binding = "DB"
database_name = "agent-arena"
database_id = "2760eae8-2ede-4c9b-a3b3-b2757637a925"
migrations_dir = "migrations"
