name = "agent-arena-close"
main = "index.js"
compatibility_date = "2026-01-01"

[triggers]
crons = ["5 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "agent-arena"
database_id = "2760eae8-2ede-4c9b-a3b3-b2757637a925"
